# Generated by Django 5.2.4 on 2025-08-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='first_website\\media\x08log/default.jpg', upload_to='blog/'),
        ),
    ]
