# Generated by Django 5.2.4 on 2025-09-05 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='massage',
            new_name='message',
        ),
    ]
